### ISSUE TITLE
Prebuilt binary reported as malware?

### ISSUE THREAD

**Issue by olee** [Tonyx97/Tomb-Raider-II-Multiplayer-Mod#14]
Any idea why I get so many reports from the prebuilt release?
https://www.virustotal.com/gui/file/66b7c456e74d4c633cd0119392e2147dd29f84e8e110df254ae42ad8fb008448

Chrome even blocks the download completely and windows deletes the dll file in the client folder when trying to access it.

**Comment by Tonyx97** [comment]
The loader injects an unsigned dll (the mod itself) and patches the game from within. That's why you get those detections, if you want to use the binaries disable chrome security to download files and disable windows defender or download the source and compile it yourself. Either way, you will have to disable or lower windows defender.
