### ISSUE TITLE
Sync - Saving/Loading/Triggers

### ISSUE THREAD

**Issue by DanzaG** [Tonyx97/Tomb-Raider-II-Multiplayer-Mod#9]
Save & Load means players will be on different states, there is also an issue with triggers repeating and enemies appear on persons screen but not another - from our testing in TombRunner this is the biggest cause of crashes. Will write up more when I think of a solution.

**Comment by Tonyx97** [comment]
This is one of the biggest issues in the mod, the sync of entities in general, I didn't find a good and stable solution for it, since this brings up a few questions such as, which state of the entities should be synced? from which player? The player that advanced the most and activated the most entities should be the one streaming the state of the objects but this would need some work to make it work properly. I've seen all your posts now but I don't really have time for it now. I was thinking on starting TR III Multiplayer with a friend and fix/add everything this current mod is lacking of. This is a hobby project for the future but it's definitely going to be a thing. There are no TR III Multiplayer mods yet, only I, IV and V afaik so it could be nice to make it for TR III, specially because of the level designing, it's quite good in my opinion and could be very cool to play with friends. I've been thinking on publishing my changes on a public server in the future so people can join it without hamachi or anything, everyone would be able to connect to the server without any problem (dedicated server with high-end hardware located in Europe). Let me know if you would like to see that in the future.

**Comment by DanzaG** [comment]
@Tonyx97 we have 2 dedicated servers set up for the multiplayer mod - feel free to join the tomb runner discord.

https://discord.gg/FRvdpBWR5C

There are quite a lot of us who are devs there too that are willing to help out.

An idea I had is since the Tomb3 source is available, that it could be refactored and redesigned to inherently support networking.

And yeah i agree it is very difficult to design a solution to this. I am still in the process of thinking of one.

**Comment by DanzaG** [comment]
And also I created these issues just to mainly document them so the ideas were not lost. As mentioned above quite a few of us would be available to help implement parts of this mod.
